spring:
  cloud:
    gateway:
      routes:
        - id: greeting-external-without-keyvault-plugin
          uri: lb://greeting-external-service-without-keyvault-plugin/
          predicates:
            - Path=/greeting-external-without-keyvault-plugin/**
        - id: greeting-external
          uri: lb://greeting-external-service/
          predicates:
            - Path=/greeting-external/**
        - id: greeting
          uri: lb://greeting-service/
          predicates:
            - Path=/greeting/**
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true

reactor:
  netty: INFO